#server:
#  port: 20000
spring:
  application:
    name: elastic8-test
  elasticsearch:
    rest:
      uris: ${ELASTICSEARCH_URIS:}
      username: ${ELASTICSEARCH_USER:}
      password: ${ELASTICSEARCH_PASSWORD:}